---
swagger: "2.0"
info:
  description: "Obtaining the London Underground stations with lifts"
  version: "1.0.0"
  title: "London Underground Lifts"
host: "virtserver.swaggerhub.com"
basePath: "/cgmora12/lifts/1.0.0"
schemes:
- "https"
paths:
  /stations:
    get:
      summary: "Finds all stations with lifts"
      description: "Return all station and their lifts"
      operationId: "getStations"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "Name of the station where it is"
        required: false
        type: "string"
      - name: "lift"
        in: "query"
        description: "Name of the lift"
        required: false
        type: "string"
      - name: "lift_direction"
        in: "query"
        description: "Direction of the lift"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Station"
      x-swagger-router-controller: "Default"
definitions:
  Station:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Westminster"
      lift:
        type: "string"
        example: "Lift Down"
      lift_direction:
        type: "string"
        example: "Down"
    xml:
      name: "Station"
