---
swagger: "2.0"
info:
  description: "Obtaining the London Underground stations with lifts"
  version: "1.0.0"
  title: "London Underground Lifts"
host: "virtserver.swaggerhub.com"
basePath: "/cgmora12/lifts/1.0.0"
schemes:
- "https"
paths:
  /stations:
    get:
      summary: "Finds all stations with lifts"
      description: "Return all station names"
      operationId: "getStations"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Station"
      x-swagger-router-controller: "Default"
  /stations/{name}:
    get:
      summary: "Find lifts by station name"
      description: "Returns the lifts found in a station"
      operationId: "getLiftsByStationName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of the station where it is"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Lift"
        400:
          description: "Invalid station name supplied"
        404:
          description: "Lifts not found"
      x-swagger-router-controller: "Default"
definitions:
  Station:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Westminster"
      lifts_number:
        type: "integer"
        format: "int64"
    example:
      lifts_number: 0
      name: "Westminster"
    xml:
      name: "Station"
  Lift:
    type: "object"
    required:
    - "clear_marked"
    - "direction"
    - "working"
    properties:
      direction:
        type: "string"
        example: "Up"
      clear_marked:
        type: "boolean"
      working:
        type: "boolean"
    example:
      clear_marked: true
      working: true
      direction: "Up"
    xml:
      name: "Lift"
